name: Deploy Forink-AI Service to EC2

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.5'

      - name: Zip sorce code
        run: |
          cd codes
          zip -r ../forink-ai.zip . -x ".git/*" ".github/*" "venv/*" "routers/.env"
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: deployment-package
          path: forink-ai.zip

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifcact
        uses: actions/download-artifact@v4
        with:
          name: deployment-package

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to S3
        run: aws s3 cp forink-ai.zip s3://${{ secrets.S3_BUCKET_NAME }}/forink-ai.zip

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            export ENV_FILE_CONTENT="${{ secrets.ENV_FILE_CONTENT }}"
            printf "%s\n" "$ENV_FILE_CONTENT" > /home/ec2-user/forink-ai/codes/routers/.env
          
            /home/ec2-user/deploy-forink-ai.sh
